# Generated by Django 4.2.4 on 2023-08-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_historias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_pasiente',
            name='cedula',
            field=models.CharField(default='000', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
