# Generated by Django 4.2.4 on 2023-08-31 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_historias', '0004_alter_registro_pasiente_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_pasiente',
            name='cedula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
