# Generated by Django 4.2.4 on 2023-08-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_historias', '0005_alter_registro_pasiente_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_pasiente',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
