# Generated by Django 4.2.4 on 2023-08-31 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_historias', '0007_alter_registro_historia_creacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registro_Pasiente',
            new_name='Registro_Paciente',
        ),
        migrations.RenameField(
            model_name='registro_historia',
            old_name='pasiente',
            new_name='paciente',
        ),
    ]
