# Generated by Django 4.2.4 on 2023-08-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_historias', '0008_rename_registro_pasiente_registro_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_paciente',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
