# Generated by Django 4.2.4 on 2023-09-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_historias', '0009_alter_registro_paciente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
