# Generated by Django 4.2.4 on 2023-09-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_historias', '0010_registro_paciente_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_historia',
            old_name='historia',
            new_name='dx_ingreso',
        ),
        migrations.RenameField(
            model_name='registro_paciente',
            old_name='cedula',
            new_name='REF_Dr',
        ),
        migrations.RenameField(
            model_name='registro_paciente',
            old_name='referido',
            new_name='cedula_madre',
        ),
        migrations.RenameField(
            model_name='registro_paciente',
            old_name='talla',
            new_name='nombre_madre',
        ),
        migrations.RemoveField(
            model_name='registro_paciente',
            name='peso',
        ),
        migrations.AddField(
            model_name='registro_historia',
            name='examen_fisico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registro_historia',
            name='laboratorio_ingreso',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro_historia',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro_historia',
            name='plan',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro_historia',
            name='ta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registro_historia',
            name='talla',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registro_paciente',
            name='antecedentes_familiares',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro_paciente',
            name='antecedentes_personales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro_paciente',
            name='enfermedad_actual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro_paciente',
            name='pn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registro_paciente',
            name='tn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
