# Generated by Django 4.2.4 on 2023-09-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_historias', '0011_rename_historia_registro_historia_dx_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_paciente',
            name='cedula_madre',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
