# Generated by Django 4.2.5 on 2023-10-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_historias', '0013_alter_registro_historia_dx_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_historia',
            name='examen_fisico',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
