# Generated by Django 4.2.5 on 2023-10-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_historias', '0015_registro_historia_evolucion_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_historia',
            name='evolucion_paciente',
            field=models.TextField(blank=True, null=True, verbose_name='Evolución del paciente'),
        ),
    ]
