# Generated by Django 4.2.5 on 2023-10-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_historias', '0016_alter_registro_historia_evolucion_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_paciente',
            name='cedula_madre',
        ),
    ]
